In [1]:
import numpy as np
import signac
import hoomd
import gsd.hoomd

In [2]:
project = signac.get_project("../")

In [7]:
def relabel_center_gsd(gsd_file,length,num_center_mol, start=0, stop=None, stride=1):
    """
    length = length of molecules
    num_center_mol = number of molecules from the bead (integer)
    """
    print("function")
    original_traj = gsd.hoomd.open(gsd_file)

    with gsd.hoomd.open("new_traj.gsd", "w") as new_traj:
        for frame in original_traj:
            frame.particles.types.append("B")
            for pos in frame.particles.position[int(length/2)::length]: 
                start_bead = frame.particles.position[int(length/2)+num_center_mol]
                print(start_bead)
                stop_bead = frame.particles.position[int(length/2)-num_center_mol]
            frame.particles.typeid[start_bead:stop_bead] = 1
            new_traj.append(frame)
    return(new_traj)

In [8]:
for job in project.find_jobs():
    if job.doc.runs != 1:
        continue
    gsd_file = job.fn("production.gsd")
    new_gsd = (relabel_center_gsd(gsd_file,length=job.doc.lengths,num_center_mol=2))

function
success?
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3.7634277]
[1.1652342 5.461268  3

ValueError: assignment destination is read-only